### ISSUE TITLE
[Feature Requested] Implement endpoint for high resolution previews

### ISSUE THREAD

**Issue by lauritsf** [NHMDenmark/Pi-Eye#4]
**Is your feature request related to a problem? Please describe.**
The Entomologui was implemented with a feature to view large previews of the PiEye cameras. This was possible as the high resolution still pictures were returned as jpg pictures.
As we have moved to raw DNG files for the still captures, this is no longer possible.

**Describe the solution you'd like**
We can implement an additional route to return high resolution preview images.
This requires adding an additional configuration.

**Difficulty estimate:**
This is relatively simple, and can be implemented in 1-2 hours.

**Describe alternatives you've considered**
An alternative would be to allow the capture endpoints to take parameters like "width", "height", "format" etc, but with our current scope and requirements, the previous suggestion would be more straightforward.

**Comment by lauritsf** [comment]
@chelseagraham, As we discussed, this is on my todo :)

**Comment by chelseagraham** [comment]
Perfect. As we chatted about, it is possible to work around without the large preview of the Pis in entomoloGUI, but it will take a long time focus each lens if you cam only use still images to guide adjustment. This is possible while we are in development. It is preferable, however, to have this working for full functionality.

**Comment by lauritsf** [comment]
This feature has been implemented in version [v0.2.0](https://github.com/NHMDenmark/Pi-Eye/tree/7df32f113cc2f3b9eb5943aad175b705847ddf28)! 🚀

**Comment by chelseagraham** [comment]
That is great! Thank you, Laurits! I'm really excited to see this next week.
